### ISSUE TITLE
Can Si sequence be different in each new round ?

### ISSUE THREAD

**Issue by AidenVii** [lechuga16/scavogl_rework#1]
such as we set must win 3 rounds in 5 ,
now the Si sequence in 1-5 round are all same , can it be set to random , or not ?

**Comment by lechuga16** [comment]
To change the number of rounds, you must modify sm_scavenge_rounds (it only supports 1,3 and 5).
Regarding that, adding randomness to the value of the number of rounds is not very complicated. I will add it.

**Comment by AidenVii** [comment]
that's cool ! man

**Comment by blueblur0730** [comment]
> such as we set must win 3 rounds in 5 , now the Si sequence in 1-5 round are all same , can it be set to random , or not ?

about SI sequence in scavenge mode please see [here](https://github.com/SirPlease/L4D2-Competitive-Rework/blob/6b840da1ed88284815946604c6349ed0766deb26/addons/sourcemod/scripting/l4d2_fix_firsthit.sp#L39)

**Comment by lechuga16** [comment]
I don't think I understood the second part, sorry :(
regarding l4d2_fix_firsthit, I remember reading it in the Target_7 repository and I don't know why I didn't add it, well now I do.

**Comment by lechuga16** [comment]
I'm seeing that sir added it to generalfixes.cfg, it's just a matter of activating it with his convar.
