### ISSUE TITLE
confgl ready up name can not be change

### ISSUE THREAD

**Issue by AidenVii** [lechuga16/scavogl_rework#2]
its be locked as "ScavOgl v2.3.1"
but i didnt find this code at any cfg files ...
when i changed it to other characters , and restart server , it did not work , like this
![RFOK~EE F9SO_{V$}DXWYB7](https://github.com/lechuga16/scavogl_rework/assets/48006618/125337a5-a6e0-42ae-913e-260cffd2cecf)

**Comment by lechuga16** [comment]
There is an add-on "scavenge_gamemode" that changes the mode from ScavOgl to ScavHunters, to make it consistent, it also modifies the cfg name.

https://github.com/lechuga16/scavogl_rework/blob/3cb987f1bdcc10f9a037e032a7e1e6d3aa86883e/addons/sourcemod/scripting/scavenge_gamemode.sp#L494

**Comment by AidenVii** [comment]
okay , dear lechuga , might i ask , will u open the way let server owners set the ready up by theirself ?

**Comment by lechuga16** [comment]
I will add a cvar to control this point
