### ISSUE TITLE
about l4d2_sacv_gascan_selfburn

### ISSUE THREAD

**Issue by blueblur0730** [lechuga16/scavogl_rework#3]
Hi! glad to see you have used some of mine modified codes.  
but I still remember this plugin sometimes don't ignite the gascan (or ignite the gascan with unexpected condition) since last time I updated it.  
I have not played l4d2 for nearly 1 year and recently I was called by some friends and I started to manage the plugins again. so when I checked this repo I noticed you added this plugin so I decided to inform you about the issue.  
  
and about this plugin, my original thought was to break the limit that it will be only used in c8m5 and add the burn limit to it. but now I think the method to found an unreachable gascan is not pretty good, very hacky.  
if you have found any problem about this plugin just let me know freely, I may put work into it if I have free time in the future.

**Comment by lechuga16** [comment]
hello, the truth was a coincidence to find your codes, I was developing a plugin for c8m5 and seeing your work I found them great. the truth is that I have not done many tests regarding the plugin and now that you mention it I will take some time to check it, if I find any solution I will send it to your repository.

**Comment by blueblur0730** [comment]
this will be safer and more accurate to hook gascans, also removed these nasty cvars. tested.  
https://github.com/blueblur0730/modified-plugins/tree/main/source/l4d2_scav_gascan_selfburn

**Comment by lechuga16** [comment]
I made some minor modifications, but it is now ready
