### ISSUE TITLE
about the readyup_scav

### ISSUE THREAD

**Issue by blueblur0730** [lechuga16/scavogl_rework#5]
If my guess is right this plugin is trying to solve the problem when the server starts with scavenge mode there is no gascan in the first round.  
Actually a lot people have already noticed this and this bug [was once reported to valve](https://github.com/ValveSoftware/Source-1-Games/issues/1616) well they did nothing.  
I remember I had a discussion on SirPlease's discord and Forgetest pointed out the main point which is that the entity `info_direcctor` didn't fire the output `OnGamePlayStart`, now I see he has [a proper fix plugin](https://github.com/Target5150/MoYu_Server_Stupid_Plugins/tree/master/The%20Last%20Stand/l4d2_fix_changelevel) with this issue. Maybe you can try this cleaner way?

**Comment by lechuga16** [comment]
readyup_scav is not currently in use, the code is left as a remnant, now, I don't remember what exactly I did in replacement of him.
